# Generated by Django 3.1.3 on 2020-12-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagen')),
                ('specialty', models.CharField(max_length=100, verbose_name='Especialidad')),
                ('experience', models.TextField(verbose_name='Experiencia')),
                ('facebook', models.CharField(max_length=100, verbose_name='Facebook')),
                ('twitter', models.CharField(max_length=100, verbose_name='Twitter')),
                ('instagram', models.CharField(max_length=100, verbose_name='Instagram')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
            ],
        ),
    ]
